sudo: required
dist: trusty

os: linux

language: c

env:
  globals:
    - TEST_NGINX_BINARY=openresty

addons:
  apt:
    packages:
    - cpanminus
    - luarocks
    - valgrind

before_install:
  - sudo luarocks install luacheck
  - luacheck -q .
  - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends openresty

script:
  - export PATH=$PATH:/usr/local/openresty/nginx/sbin
  - openresty -V
  - prove -r t
  - bash test_with_valgrind.sh
